// Generic constants
export const CREATE_USER = 'CREATE_USER'
export const EMAIL = 'EMAIL'
export const ERROR = 'ERROR'
export const FACEBOOK = 'FACEBOOK'
export const GITHUB = 'GITHUB'
export const GOOGLE = 'GOOGLE'
export const PROVIDER = 'PROVIDER'
export const SUCCESS = 'SUCCESS'

// Input fields
export const AVATAR_URL = 'photoURL'
export const BANNER_URL = 'bannerURL'
export const BEHANCE = 'behance'
export const DRIBBBLE = 'dribbble'
export const FACEBOOK_URL = 'facebookURL'
export const LINKEDIN_URL = 'linkedinURL'
export const PORTFOLIO = 'portfolio'
export const SKILLS = 'skills'
export const SPECIALTY = 'specialty'
export const STATUS = 'status'
export const TWITTER_URL = 'twitterURL'

// Statuses
export const NOT_WORKING = 'Not Working'
export const REALLY_LIGHT = 'Really Light'
export const KINDA_LIGHT = 'Kinda Light'
export const NOT_THAT_BUSY = 'Not That Busy'
export const KINDA_BUSY = 'Kinda Busy'
export const REALLY_BUSY = 'Really Busy'
export const SLAMMED = 'Slammed'
