const CHANGE_AUTH = 'CHANGE_AUTH'
const CREATE_USER_WITH_EMAIL = 'CREATE_USER_WITH_EMAIL'
const LOG_IN_WITH_PROVIDER = 'LOG_IN_WITH_PROVIDER'
const LOG_IN_WITH_PROVIDER_SUCCESS = 'LOG_IN_WITH_PROVIDER_SUCCESS'
const LOG_IN_WITH_PROVIDER_FAIL = 'LOG_IN_WITH_PROVIDER_FAIL'
const SET_PROFILE_BANNER = 'SET_PROFILE_BANNER'
const SET_CURRENT_USER = 'SET_CURRENT_USER'

export {
  CHANGE_AUTH,
  CREATE_USER_WITH_EMAIL,
  LOG_IN_WITH_PROVIDER,
  LOG_IN_WITH_PROVIDER_SUCCESS,
  LOG_IN_WITH_PROVIDER_FAIL,
  SET_PROFILE_BANNER,
  SET_CURRENT_USER,
}
