const CHANGE_AUTH = 'CHANGE_AUTH'
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const CREATE_USER_WITH_EMAIL = 'CREATE_USER_WITH_EMAIL'

export {
  CHANGE_AUTH,
  CREATE_USER_WITH_EMAIL,
  SET_CURRENT_USER
}
